language: Java
jdk:
  - oraclejdk8
  - openjdk7
  - oraclejdk7
  - openjdk6

notifications:
  email:
    - java-apns@frohwalt.de
before_install:
  - wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
  - unzip -qq apache-maven-3.3.9.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
